// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

/**
 * @title  CertificateRegistry
 * @author CertChain
 * @notice Stores and verifies educational certificates on-chain.
 *
 *         Design decisions:
 *         - Only the contract owner (backend wallet) can issue or revoke.
 *         - User/institution management is handled by the Java microservice.
 *         - Anyone can verify a certificate — no auth required.
 *         - Actual PDF files live on IPFS; only the hash + CID are stored here.
 */
contract CertificateRegistry is Ownable, Pausable {

    // ─────────────────────────────────────────────────────────────
    //  ENUMS
    // ─────────────────────────────────────────────────────────────

    enum CertificateStatus {
        Active,   // 0 — certificate is valid
        Revoked   // 1 — certificate has been revoked
    }

    // ─────────────────────────────────────────────────────────────
    //  STRUCTS
    // ─────────────────────────────────────────────────────────────

    struct Certificate {
        string            certId;           // Unique ID generated by Java backend (e.g. UUID)
        bytes32           documentHash;     // keccak256 hash of the original PDF
        string            ipfsCID;          // IPFS CID — pointer to the actual PDF
        string            institutionId;    // Institution ID from Java microservice
        string            studentId;        // Student ID from Java microservice
        string            studentName;      // Full name of the student
        string            courseName;       // Course / degree / programme name
        uint256           issuedAt;         // Block timestamp when certificate was issued
        CertificateStatus status;           // Active or Revoked
    }

    // ─────────────────────────────────────────────────────────────
    //  STATE VARIABLES
    // ─────────────────────────────────────────────────────────────

    // certId => Certificate
    mapping(string => Certificate) private _certificates;

    // documentHash => certId  (for PDF hash verification)
    mapping(bytes32 => string) private _hashToCertId;

    // studentId => list of certIds  (for fetching a student's certificates)
    mapping(string => string[]) private _studentCertificates;

    // institutionId => list of certIds  (for fetching an institution's certificates)
    mapping(string => string[]) private _institutionCertificates;

    // certId => exists flag  (cheaper duplicate check)
    mapping(string => bool) private _certIdExists;

    // Global counters
    uint256 public totalCertificates;

    // ─────────────────────────────────────────────────────────────
    //  EVENTS
    // ─────────────────────────────────────────────────────────────

    event CertificateIssued(
        string  indexed certId,
        bytes32 indexed documentHash,
        string          institutionId,
        string          studentId,
        string          courseName,
        uint256         timestamp
    );

    event CertificateRevoked(
        string  indexed certId,
        address indexed revokedBy,
        uint256         timestamp
    );

    // ─────────────────────────────────────────────────────────────
    //  MODIFIERS
    // ─────────────────────────────────────────────────────────────

    modifier certMustExist(string memory certId) {
        require(_certIdExists[certId], "CertRegistry: certificate not found");
        _;
    }

    // ─────────────────────────────────────────────────────────────
    //  CONSTRUCTOR
    // ─────────────────────────────────────────────────────────────

    /**
     * @dev The deploying wallet becomes the owner.
     *      In production this will be your Java backend wallet.
     */
    constructor() Ownable(msg.sender) {}

    // ─────────────────────────────────────────────────────────────
    //  WRITE FUNCTIONS  (owner / backend wallet only)
    // ─────────────────────────────────────────────────────────────

    /**
     * @notice Issue a new certificate on-chain.
     *         Called by the Java backend after it has validated the request.
     *
     * @param certId        Unique certificate ID (UUID from Java backend)
     * @param documentHash  keccak256 hash of the PDF document
     * @param ipfsCID       IPFS Content Identifier where the PDF is stored
     * @param institutionId Institution ID (from Java microservice DB)
     * @param studentId     Student ID (from Java microservice DB)
     * @param studentName   Full name of the student
     * @param courseName    Name of the course / degree
     */
    function issueCertificate(
        string  calldata certId,
        bytes32          documentHash,
        string  calldata ipfsCID,
        string  calldata institutionId,
        string  calldata studentId,
        string  calldata studentName,
        string  calldata courseName
    ) external onlyOwner whenNotPaused {

        // ── validations ──────────────────────────────────────────
        require(!_certIdExists[certId],
            "CertRegistry: certId already exists");
        require(documentHash != bytes32(0),
            "CertRegistry: document hash cannot be empty");
        require(bytes(ipfsCID).length > 0,
            "CertRegistry: IPFS CID cannot be empty");
        require(bytes(institutionId).length > 0,
            "CertRegistry: institutionId cannot be empty");
        require(bytes(studentId).length > 0,
            "CertRegistry: studentId cannot be empty");
        require(bytes(studentName).length > 0,
            "CertRegistry: student name cannot be empty");
        require(bytes(courseName).length > 0,
            "CertRegistry: course name cannot be empty");
        require(bytes(_hashToCertId[documentHash]).length == 0,
            "CertRegistry: this document is already registered");

        // ── store ────────────────────────────────────────────────
        _certificates[certId] = Certificate({
            certId:        certId,
            documentHash:  documentHash,
            ipfsCID:       ipfsCID,
            institutionId: institutionId,
            studentId:     studentId,
            studentName:   studentName,
            courseName:    courseName,
            issuedAt:      block.timestamp,
            status:        CertificateStatus.Active
        });

        _certIdExists[certId]         = true;
        _hashToCertId[documentHash]   = certId;

        _studentCertificates[studentId].push(certId);
        _institutionCertificates[institutionId].push(certId);

        totalCertificates++;

        emit CertificateIssued(
            certId,
            documentHash,
            institutionId,
            studentId,
            courseName,
            block.timestamp
        );
    }

    /**
     * @notice Revoke an existing certificate.
     *         Called by the Java backend when an institution or admin requests it.
     *
     * @param certId The ID of the certificate to revoke
     */
    function revokeCertificate(string calldata certId)
        external
        onlyOwner
        certMustExist(certId)
        whenNotPaused
    {
        require(
            _certificates[certId].status == CertificateStatus.Active,
            "CertRegistry: certificate is already revoked"
        );

        _certificates[certId].status = CertificateStatus.Revoked;

        emit CertificateRevoked(certId, msg.sender, block.timestamp);
    }

    // ─────────────────────────────────────────────────────────────
    //  VERIFICATION FUNCTIONS  (public — no auth needed)
    // ─────────────────────────────────────────────────────────────

    /**
     * @notice Verify a certificate by its unique ID.
     *         Used when scanning a QR code or entering a certificate number.
     *
     * @param  certId      The certificate ID to look up
     * @return isValid     true if the certificate exists and is Active
     * @return status      0 = Active, 1 = Revoked
     * @return institution Institution ID that issued the certificate
     * @return student     Name of the student
     * @return course      Name of the course
     * @return issuedAt    Unix timestamp of issuance
     * @return ipfsCID     IPFS CID to fetch the original PDF
     */
    function verifyCertificateById(string calldata certId)
        external
        view
        returns (
            bool    isValid,
            uint8   status,
            string  memory institution,
            string  memory student,
            string  memory course,
            uint256 issuedAt,
            string  memory ipfsCID
        )
    {
        if (!_certIdExists[certId]) {
            return (false, 1, "", "", "", 0, "");
        }

        Certificate storage cert = _certificates[certId];

        isValid     = cert.status == CertificateStatus.Active;
        status      = uint8(cert.status);
        institution = cert.institutionId;
        student     = cert.studentName;
        course      = cert.courseName;
        issuedAt    = cert.issuedAt;
        ipfsCID     = cert.ipfsCID;
    }

    /**
     * @notice Verify a certificate by hashing the uploaded PDF.
     *         Used when someone uploads the original PDF to prove authenticity.
     *
     * @param  documentHash keccak256 hash of the uploaded PDF
     * @return isValid      true if hash matches an Active certificate
     * @return certId       The certificate ID linked to this hash
     */
    function verifyCertificateByHash(bytes32 documentHash)
        external
        view
        returns (bool isValid, string memory certId)
    {
        certId = _hashToCertId[documentHash];

        if (bytes(certId).length == 0) {
            return (false, "");
        }

        isValid = _certificates[certId].status == CertificateStatus.Active;
    }

    // ─────────────────────────────────────────────────────────────
    //  GETTER FUNCTIONS
    // ─────────────────────────────────────────────────────────────

    /**
     * @notice Get the full details of a certificate by ID.
     */
    function getCertificate(string calldata certId)
        external
        view
        certMustExist(certId)
        returns (Certificate memory)
    {
        return _certificates[certId];
    }

    /**
     * @notice Get all certificate IDs issued to a student.
     * @param  studentId  Student ID from the Java microservice
     */
    function getStudentCertificates(string calldata studentId)
        external
        view
        returns (string[] memory)
    {
        return _studentCertificates[studentId];
    }

    /**
     * @notice Get all certificate IDs issued by an institution.
     * @param  institutionId  Institution ID from the Java microservice
     */
    function getInstitutionCertificates(string calldata institutionId)
        external
        view
        returns (string[] memory)
    {
        return _institutionCertificates[institutionId];
    }

    /**
     * @notice Check whether a certId already exists on-chain.
     */
    function certificateExists(string calldata certId)
        external
        view
        returns (bool)
    {
        return _certIdExists[certId];
    }

    // ─────────────────────────────────────────────────────────────
    //  EMERGENCY CONTROLS  (owner only)
    // ─────────────────────────────────────────────────────────────

    /**
     * @notice Pause all write operations — emergency use only.
     */
    function pause() external onlyOwner {
        _pause();
    }

    /**
     * @notice Resume normal operations after a pause.
     */
    function unpause() external onlyOwner {
        _unpause();
    }
}
